name: fastaagent
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.1.0
  fl_country_code_picker: ^0.1.5
  image_picker: ^1.0.0
  image_cropper: ^5.0.0
  qr_flutter: ^4.1.0
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  share_plus: ^7.1.0
  intl: ^0.18.0
  timeago: ^3.5.0
  cached_network_image: ^3.2.3
  firebase_messaging: ^14.6.9
  firebase_core: ^2.23.0
  upgrader: ^8.3.0
  awesome_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0
flutter_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: "assets/images/fastaagentLogo.png"
  adaptive_icon_foreground: "assets/images/fastaagentLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
